# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  zip:
    image: zip
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Zip_Pay_Api786"
        ACCEPT_EULA: "Y"